-- 1. Find out which customers have not placed any orders
SELECT Customers.FirstName, Customers.LastName
FROM Customers
LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
WHERE Orders.OrderID IS NULL;

-- 2. Find the total number of products available for sale
SELECT COUNT(*) AS TotalProducts
FROM Products;

-- 3. Calculate the total revenue generated by TechShop
SELECT SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
FROM OrderDetails
JOIN Products ON OrderDetails.ProductID = Products.ProductID;

-- 4. Calculate the average quantity ordered for products in a specific category
SELECT AVG(OrderDetails.Quantity) AS AverageQuantityOrdered
FROM OrderDetails
JOIN Products ON OrderDetails.ProductID = Products.ProductID
JOIN Categories ON Products.CategoryID = Categories.CategoryID
WHERE Categories.CategoryName = 'CategoryName';

-- 5. Calculate the total revenue generated by a specific customer
SELECT SUM(Orders.TotalAmount) AS TotalRevenue
FROM Orders
WHERE Orders.CustomerID = 'CustomerID';

-- 6. Find the customers who have placed the most orders
SELECT Customers.FirstName, Customers.LastName, COUNT(Orders.OrderID) AS OrderCount
FROM Orders
JOIN Customers ON Orders.CustomerID = Customers.CustomerID
GROUP BY Customers.CustomerID
ORDER BY OrderCount DESC
LIMIT 1;

-- 7. Find the most popular product category with the highest total quantity ordered
SELECT Categories.CategoryName, SUM(OrderDetails.Quantity) AS TotalQuantityOrdered
FROM OrderDetails
JOIN Products ON OrderDetails.ProductID = Products.ProductID
JOIN Categories ON Products.CategoryID = Categories.CategoryID
GROUP BY Categories.CategoryName
ORDER BY TotalQuantityOrdered DESC
LIMIT 1;

-- 8. Find the customer who has spent the most money on electronic gadgets
SELECT Customers.FirstName, Customers.LastName, SUM(OrderDetails.Quantity * Products.Price) AS TotalSpending
FROM OrderDetails
JOIN Orders ON OrderDetails.OrderID = Orders.OrderID
JOIN Customers ON Orders.CustomerID = Customers.CustomerID
JOIN Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY Customers.CustomerID
ORDER BY TotalSpending DESC
LIMIT 1;

-- 9. Calculate the average order value (total revenue divided by the number of orders) for all customers
SELECT Customers.FirstName, Customers.LastName, AVG(Orders.TotalAmount) AS AverageOrderValue
FROM Orders
JOIN Customers ON Orders.CustomerID = Customers.CustomerID
GROUP BY Customers.CustomerID;

-- 10. Find the total number of orders placed by each customer and list their names along with the order count
SELECT Customers.FirstName, Customers.LastName, COUNT(Orders.OrderID) AS OrderCount
FROM Orders
JOIN Customers ON Orders.CustomerID = Customers.CustomerID
GROUP BY Customers.CustomerID;
